### ISSUE TITLE
Field name testing results: special characters and numbers (and blanks)

### ISSUE THREAD

**Issue by dbloom** [VertNet/bels#28]
In an attempt to determine how BELS reads and responds to submitted field names I submitted approximately 50-60 small datasets, all using the demo dataset provided in this repo, https://github.com/VertNet/bels/blob/main/data/tests/test_demo.csv.

Testing methods:  To test BELS' response I added special characters and numbers to the start of one or more field names in the following ways:

1. a single special character at the start one field (7 Characters used: ! # $ ^ * - / )
2. a double special character at the start of one field ( !! )
3. a single number (1) or a double number (11) at the start of one field
4. special characters at the start of alternating field names ( !country,county,#stateprovince )
5. special characters at the start of consecutive field names ( !country,#county,stateprovince)
6. special characters and numbers at the start of alternating field names ( !country,county,1stateprovince )
7. special characters and numbers at the start of consecutive field names ( !country,1county,stateprovince)
8. single blank field and multiple blank fields
9. single and multiple spaces at the start of field names

OUTPUT FILE NOT RETURNED:

Files uploaded with blank field names in two or more consecutive columns did not return an output file for any test.

All tests in which special characters and numbers started field names in consecutive columns did not return an output file for any test.

Examples:  continent,!country,1countrycode,stateprovince  OR continent,1country,2countrycode,stateprovince OR continent,!country,#countrycode,stateprovince OR continent,!country,!countrycode,stateprovince

OUTPUT FILE RETURNED:

Spaces at the start of field names:

In all cases single and double spaces were removed from the field name by BELS. This was true whether spaces were present in sequential or non-sequential fields.

Blank field names:

Where blank spaces were present as a single field in the file or as multiple fields that were non-sequential, an output file was returned. Blank fields were named as "UNNAMED_COLUMN_1", "UNNAMED_COLUMN_2" and so on.

Special characters and numbers (individually, multiples, and mixed):

Where one or more special characters or numbers were present at the beginning of one or more non-consecutive columns an output file was returned.

Examples:  continent,!country,countrycode,1stateprovince  OR continent,1country,countrycode,2stateprovince OR continent,!country,countrycode,#stateprovince OR continent,!country,countrycode,!stateprovince

BELS converted all special characters into underscores and added a preceding underscore so that field names beginning with a special character were modified to begin with two underscores. When numbers were present at the start of the field name, the number was maintained, but a preceding underscore was added. When a double special character was added to the beginning of a field name, BELS replaced both with underscores, plus a preceding underscore.

"!country" modified to "__country"
"!!country" modified to "___country"
"1country" modified to "_1country"
"11country" modified to "_11country"

A zip file containing some sample data files uploaded to BELS along with their corresponding output files, will be sent to @tucotuco with the file name "BELS_Uploads_Results.zip". A second file will be sent containing some sample data files that did not produce output files, "BELS_Uploads_NOResults.zip". I will retain all test data files for reference as needed.

**Comment by tucotuco** [comment]
All cases of files that did not return results had no interpretable country fields. This condition has been trapped by the web app so that they will not be sent on to BigQuery. Fixed in a9c0dac6299ebebd1dbd13cbf4c2a01d4c49ff1b.
