### ISSUE TITLE
BELS returns countryCode in country field

### ISSUE THREAD

**Issue by dbloom** [VertNet/bels#32]
Results from BELS test attached.

In lines 9 and 10 for Denmark and Ireland, match_country contains countryCodes instead of country names. It may be something to do with the inputs, specifically this issue appears only in records for which a countryCode was provided as a verbatim input in the upload file. Records without countryCode in the upload do not appear to have this issue.

If additional testing of this with additional records that contain a verbatim countryCode are required, please let me know.

[dbloom_test1-44693381-cd50-44de-a0d6-4509a9dd0856.csv](https://github.com/VertNet/bels/files/8710341/dbloom_test1-44693381-cd50-44de-a0d6-4509a9dd0856.csv)

**Comment by tucotuco** [comment]
@dbloom Several questions. 

First, the match strings contain continent information, which should not happen with the most recent changes. Continent values are explicitly excluded. Is this file the result of a run before the latest changes?

Second, the match_country is the value used to divine the ISO-2-letter country code to use in matching. There is a priority process for making the determination of what to look up. The code for this choice can be found at https://github.com/VertNet/bels/blob/main/bels/bels_query.py#L176. The values you mentioned are the ones that would be expected for those records.

Third, can you include or point to the input file used to get this result?

Fourth, given the above, do you still see there to be any problem?

**Comment by tucotuco** [comment]
Done in 07eea82a3ebb6a9b55a0240f28027e0a621ce4d5.
